sudo: required
language: python
python:
  - "3.5"

before_install:
  - printenv | grep -E '^TRAVIS_' > .env
  - sudo apt-get install -y build-essential wget git python3-pip python3-cffi
  - sudo pip3 install -U pip setuptools

script:
  - sudo python3 setup.py install

after_success:
  - cd plugin_packaging && ./build_plugin.sh && cd ..

deploy:
  provider: releases
  api_key: ${TRAVIS_GH_TOKEN}
  file: "plugin_packaging/identitySHARK_plugin.tar"
  skip_cleanup: true
  on:
    repo: smartshark/linkSHARK
    tags: true
